{% set name = "pycwt" %}
{% set version = "0.4.0b0" %}
{% set sha256 = "f337cd28531f5b49a62b5f3ba5657cbc3e2f69e15a12ee3d309a2aa5ca1b8e86" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python
    - setuptools
  run:
    - python
    - numpy
    - scipy
    - tqdm

test:
  imports:
    - pycwt
    - pycwt.helpers

about:
  home: https://github.com/regeirk/pycwt
  license: BSD-3-clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: A Python module for continuous wavelet spectral analysis

  description: |
    A Python module for continuous wavelet spectral analysis. It includes
    a collection of routines for wavelet transform and statistical analysis
    via FFT algorithm. In addition, the module also includes cross-wavelet
    transforms, wavelet coherence tests and sample scripts.
  doc_url: http://pycwt.readthedocs.io/
  dev_url: https://github.com/regeirk/pycwt

extra:
  recipe-maintainers:
    - saketkc
