travis:
  secure:
    BINSTAR_TOKEN: WWVrzG81eRobilRGrKbTVRty4VIBCktbaKqryEPQ5wCgUOs8Jqpua9ze/4GpwZVgT9tH48vQfCKWNzvBbXNt2QJsdehRoZjoW9qEtvD+CIQhNtCAUiv8xiD/uWu4HfZFrSzP5FKr0kN5JRivmQWQquKMJAPYB9LiamNEee1nJMpbbJ864L7Hkj3knQ24jo510KtlKS4YscLX6lXgMaarc7yxq4ZwGG2+ZCzX46XCLL25GzUOoHvKomPZOEd+yqaL0idykeu89rEtHJgOGNXG0qAxFRnActMz4OvhbE2ElhHkzIVwQjGqqO1XdxRTVuWub55TEx8Iwd0bqVpFSjg0EM6exZMINtpM9ypD0OvB1Q4wAeyXWMh1pyAdt4HBQvWoWWEac0DNP5f78FmfNkXqPxtclstkgGJ4F96jGUJeUc+6qTIhF3B6xyBbvlzwH3bmsgxSmmRmFUwUwpYMAq6bWQ5RMmJ0S2lPc/M3T/g4fza0+ziW8RFF5ZTev8QaEp6Shjk08HXcgs16u1tUvMX86BOa/vniAoTBwMDibayZslo4lnnUjskLjBFP0W8/D6L/kOiAQ8taRf+/1Q6fGpHTsaudxoZMKX+kMBy0fALld2E0NMVJHxX2FkA93iZNmK2Advuy2U+rjgk60nQ0A7Wr1JVQDVVCvUZtgjwfo5of19U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
