travis:
  secure:
    BINSTAR_TOKEN: KGxYwNR9DBXj4AttZV9qOYOr94f56mJw4WGB1YjCsrFNMz3cYFjuZPXMqWYHLPxtoSgZMjOudOA9p2PaaFZqgY7xCd0PKW4WVSfMNOrW2UGbjqrK0V+xZy3uGgP+5FjTeFD2lmJ2SI3MpTHCqQa6yueBh1T+pVrJpntkuBcbSCf4QIbEe9jQ8mYDJMcR/yWnH0ECFMbI7LNlOahKJbDwtOPL8pe5BzzsE0KUWPx5sOxK9i7dWs7mEw8ZxXGtsCB6/GLNfU1/7NGKN+/4OMGjHb2GeZKzw4LmQ/1BUowWko8dS3QHtWsPOMSgySAu2pUv1KEBWxPVhwVtR6tlfzS4Jo1zbw67bihb8BHc0kINqjm4Q9Ah6a1xtEkItZ3M+3aaP4FvtNWf5g7ejoZLBv+XXUVDMDBah71MAOKKkmWzOvjy5NfA0UNO9WGyevhEO+qDTnzpmlOkykEIEqVOfHLU3LeDtsjzQJt8R+7ilVPuDqygaWrCLzp/eA4Ap+arPz4cbanIWbiYmSC2sl1ykNs9EA6gNPKv/nOEhBXzUopN9IBbmE1wH9REYXjqrcC11uRLQPi7xqUA2d66U2Bq1X+EiN2nkKwM4H4Qni05OZjgXl9ACXWDxxpkO9VyMyYicAP9ECg5PrFTIutqtFhNSG5XA9alJA/5X7gvmlQ/kh+dTOY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
