travis:
  secure:
    BINSTAR_TOKEN: ErujCtNTKvwz9GvPr1f+U+aXFH9diF18CRChoRMHGLtRseQW33dVScOf3Wc0hKRdlSR7EK4XYdOqjO5Qtyb5/jz0ge/zQvXYr0yjQXV7WsrjndYI3FTcYl6STgRfiK08lKfzRI8WGmjKgWaxmeljUILrcpUqiU4M8hbBlph/IrBdbqBpLNPRaNpaW8sIcfVVfQyQgK2CcJBm7ejOKIgpJhJftgg3wZ3qD/dYbXmuW3a3PDDrMp3wjeT7j4nVnRaUEpEPkre9VdqJzsfC0D1Wg5Rr/amsQrWJfXvlgGHxkfQsds+u1vWWSV6P9YMixssPubI59zjmkYWs8k8YyflPDuEw2EPxGWtZsx3+O4o4hgPM/1hbKGJwj4l9KqlBuNtpN7wtaxBs971AVCoFPup1lnfcCzbYqK7IGf38rnR0BvzX59P/Gjadkp44NzWAq4yFgDHLHJPLh14JE3hniLzieyZJfJFaWFOoSwbwDooj5wqTC2nR818Ax1JtV77ty3vtNyv7bXpPayAbICUXMaGRG765sUJ3dugzh3ABRERNc/Bd2DBk1MN8PWg72ykcRcLp0lmjs1gklRBVPp8cCAAlD4o6K77rWusoFM8IBxzTha5y31eS/Ox3Fjm5Jc1lZEkYyFjfRvSw3l6oD2p1KVeL8Jut/kss+zdDOAeDnlwJIcE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
