travis:
  secure:
    BINSTAR_TOKEN: n55Hlz5Lee8ouOBdAwEt2JdI7M8QiaXbuTnaMA0h7ldJrCJCrW2F7pkCqXw9rHc1RhLO2y7rOslv6n9b5BeYVz/lhhrPKjDp0NL4JKgUQOxJ50TYFUHfmAReHTDWfSRc4pTxLDfSVZlZ/BtGMgHNmd55DAcNaJzrzUnWZlK5wBHMB0ToqePjMbjanC3XmbGhHPtzV4sNC26fRPH0pCuHipqJcpg7t8pQ1QJiKpMMRwPtKktY86Uz3kpo+ql8Zxjlipu/rTx7G0rzjxzLmaLWh6x0KhMKdfCF7xI8CDbxhxnZOtTfwkWX8ranUnCUbsgxEDwxGxwRF0MGeEULQYYOcUaUPBHVx9Keg63kOkmHj7wkQlA+CyZ65jqby85B3q23FcK0Z+XtO8E4Dxsg1UPIxpa/KkViQnZd/gDhMBmXXExzKMVjlci89aCaglRwyEVURbaG9sLsSOokieLf9pzNq03bvae8uz7kZnhZ8jbHr4CXCRhZ/LqbTtovqRKBxJHhtGmGfdc4KCaCvn4hSNq6aJSHJDOySmQw8uR/WjTIbxhRoEjfVTRKY40uAvYYgB9wyckfMcMksZ9keGvI/dg+/UU9bZzxUhFtrdhIOW962F53k9r9e3yHkEP3/eZZfycg2wM55fAdg1jFHOBaccZRHtsGvcxVKfTtvBnrgRA88Vs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
