travis:
  secure:
    BINSTAR_TOKEN: IMNmp/9guY3GI64hoM++bFyjMuPk11bLaFx4x0u/bblFkWsVTnsRj7FWblR2RpgC18MMbmxaFQNKwE9gOp5mIW29yaItytF5P1m5N1ad/wWmVZcNOn8N/vSj1diMaorUgIb1hNj9FDdtfp9Ail4glkTA02RLNhtfIX9p9llfDDswqs4AS18syfT/R2e4PfscdwbISMSEZmuBOK2T8UDWBaET88o+iYcsnjOKyty1yQ6gnCDi7yLZHMc09UNmmJHADtD0xeqNG97Mbz0gEejoa8QeWHQXeYS8kTGqHFPO0bpB84B4WVNLpPx77AQBNNUmXigKruoU9+7z8drP71zmBCakmi4YipWx+V66iVRJlAMIhGeHmLW+hOYiQjFUC7oxgU1mX2Da0H1qN5r0a4zgA/fYLRRygZyLJvzNzm+KcJqwg4YbLH4Dsz7ycdQRtm7nfuUF9aQSan2BuoDUU550T9noQp19FFzG1DIkhIVeRJ2JNlRErFr0geD4FSRSFSQ5+3+OBLaxCgW3G+qOXH0SRjIghgEsvn981+/ga6v5CjaHSMGyqxcSdjuHCPzplVXubIQy/s+UXgU60GlX7kZAzcl+CKRu0JeAj4vJ1vDM5DhuLvHjiSOtiufSj0IEL+NPMN+Kx+afd8LlwDEg+CmmXxFse9cFX8VCJ5QJB5QX10U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
